ALTER TABLE agent_alert_state
  ADD COLUMN IF NOT EXISTS cpu_alert_active BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS mem_alert_active BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS last_cpu_alert_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_mem_alert_at TIMESTAMPTZ;
